spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 112001
    url: jdbc:mysql://localhost:3306/hrs?characterEncoding=utf8&useSSL=false&autoReconnect=true&useUnicode=true&serverTimezone=UTC
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
server:
  servlet:
    context-path: /order